import Footer from "@/components/FooterScreen";
import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "WaveX AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/jpg" href="/favicon.jpg" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className="sticky top-0" style={{ zIndex: 10000000 }}>
          <Navbar />
        </div>
        {children}
        <Footer />

      </body>
    </html>
  );
}
